### ISSUE TITLE
Negative address pointer fails WriteProcessMemory

### ISSUE THREAD

**Issue by kirill-21** [timsneath/win32#310] opened 2021-09-25 18:25 UTC
```
int writeProcessMemory(int lpBaseAddress, int value) {
  final Pointer<Int32> lpBuffer = calloc<Int32>();
  lpBuffer.value = -1; // Good, value can be negative

  final int result = WriteProcessMemory(
    activeHandle,
    Pointer<Int32>.fromAddress(-69795452), // Not good, for unknown reason negative address with dart ffi causes a fail
    lpBuffer,
    sizeOf<Int32>(),
    nullptr,
  );

  calloc.free(lpBuffer);
  return result; // returns 0
}
```

The same execution with ffi from other languages(for example php/java) successfully handles such ProcessMemoryWrites 
![image](https://user-images.githubusercontent.com/63228361/134782473-e8e43c1e-a613-4933-926a-a1e9a211c49a.png)

This address (-69795452) truly exists in the process and can be written

**Comment by timsneath** [comment] 2021-09-27 21:09
Sorry -- I'm confused. Why do you want to write to a "negative address"? 

Presumably other languages overflow that to `Int64.MAX-abs(address)` on a 64-bit system. Is that what you're expecting?

**Comment by kirill-21** [comment] 2021-09-28 08:41
> Sorry -- I'm confused. Why do you want to write to a "negative address"?
> 
> Presumably other languages overflow that to `Int64.MAX-abs(address)` on a 64-bit system. Is that what you're expecting?

Process i'm writing to is 32bit, i have to use Int32 values. I want to write a negative address because address i need to write is negative

**Comment by timsneath** [comment] 2021-09-29 11:55
The 32-bit address space is from `0000:0000` to `FFFF:FFFF`; there's no such thing as a negative address. Other languages may choose to wrap around a negative address to the positive equivalent, but that's not a bug in Dart or FFI, I don't think.

Your code doesn't produce the right address. You want something more like this:
https://dartpad.dev/?id=72a720631456c133c5c875c27882fedb&null_safety=true

Hope this is helpful. Closing the issue since it's unrelated to Win32.

**Closed by timsneath** 2021-09-29 11:55 UTC
